#!/bin/bash
mount /dev/mmcblk0p1 /mnt
echo "Copy modified BOOT partition file(s) to /mnt"
echo "zedboard/images/BOOT.BIN"
echo "linux-digilent/devicetree.dtb"
echo "linux-digilient/arch/arm/boot/zImage"
echo -n "Type any key and hit enter once finished"
read foo
umount /mnt
reboot
