#!/bin/bash
mount /dev/mmcblk0p1 /mnt
echo "Run scp_boot_zed on the VM and follow the prompts in order to copy modified BOOT partition file(s) to /mnt"
echo -n "Type any key and hit enter once finished"
read foo
umount /mnt
reboot
